name: KinanAexlaAldrein_app_server
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/KinanAexlaAldrein/KinanAexlaAldrein_app
repository: https://github.com/KinanAexlaAldrein/KinanAexlaAldrein_app
issue_tracker: https://github.com/KinanAexlaAldrein/KinanAexlaAldrein_app/issues 
documentation: https://youtube.com/@KinanAexlaAldrein
funding:
  - https://github.com/sponsors/KinanAexlaAldrein


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - KinanAexlaAldrein_app
#   - KinanAexlaAldrein_app_flutter
#   - KinanAexlaAldrein_app_dart
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
